using System;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Tmds.DBus.Protocol;
using Tmds.DBus.SourceGenerator;
using System.Linq;

namespace Avalonia.FreeDesktop
{
    /// <summary>
    /// Handles D-Bus introspection for AT-SPI objects
    /// This allows accessibility tools to discover our objects
    /// </summary>
    internal class AtspiIntrospectionHandler : OrgFreedesktopDBusIntrospectableHandler
    {

        private readonly Connection _connection;

        // Custom introspection XML (standards-compliant, no unwanted attributes)
        private static readonly string CustomIntrospectionXml =
            "<?xml version=\"1.0\"?>\n<!-- Introspection generated by avinashkhatri-dev -->\n<node>\n  <interface name=\"org.freedesktop.DBus.Introspectable\">\n    <method name=\"Introspect\">\n      <arg name=\"xml_data\" type=\"s\" direction=\"out\"/>\n    </method>\n  </interface>\n</node>";

        // Hide base IntrospectXml property (not virtual in base)
        public new ReadOnlyMemory<byte> IntrospectXml => System.Text.Encoding.UTF8.GetBytes(CustomIntrospectionXml);

        public AtspiIntrospectionHandler(Connection connection, string introspectionXml) : base()
        {
            _connection = connection;
            Console.WriteLine($"[AtspiIntrospectionHandler] 🔧 Created introspection handler for connection: {connection?.GetHashCode()}");
        }

        public override Connection Connection
        {
            get
            {
                Console.WriteLine($"[AtspiIntrospectionHandler] Connection property accessed: {_connection?.GetHashCode()}");
                return _connection;
            }
        }

        protected override async ValueTask<string> OnIntrospectAsync(Message request)
        {
            Console.WriteLine($"[AtspiIntrospectionHandler] OnIntrospectAsync called for message: {request}");
            Console.WriteLine($"[AtspiIntrospectionHandler] Returning introspection XML (from IntrospectXml property):\n{CustomIntrospectionXml}");
            return CustomIntrospectionXml;
        }
    }
}
